// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpz0YeMhxXwCO39fognthNL0hyztcPNgU',
    appId: '1:212214398916:android:56b9db4e84c71cdab26e91',
    messagingSenderId: '212214398916',
    projectId: 'bolao-copa-do-mundo-salles',
    storageBucket: 'bolao-copa-do-mundo-salles.firebasestorage.app',
  );

  }

  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ7tSS1UR7ZQWZA4HknxQP2k_krXVamEg',
    appId: '1:212214398916:web:218dc04cbb2318cdb26e91',
    messagingSenderId: '212214398916',
    projectId: 'bolao-copa-do-mundo-salles',
    authDomain: 'bolao-copa-do-mundo-salles.firebaseapp.com',
    storageBucket: 'bolao-copa-do-mundo-salles.firebasestorage.app',
    measurementId: 'G-SW7PRWHM56',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVIjPKmxcaiVN1x0zEQOJVZUd8CqfOMRE',
    appId: '1:212214398916:ios:b9d3161018a1be4eb26e91',
    messagingSenderId: '212214398916',
    projectId: 'bolao-copa-do-mundo-salles',
    storageBucket: 'bolao-copa-do-mundo-salles.firebasestorage.app',
    iosClientId: '212214398916-j17cmqger48mjdvf3ithep459p2aabuj.apps.googleusercontent.com',
    iosBundleId: 'com.salles.bolaocopadomundo',
  );

}